//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_Management_System.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARMODEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARMODEL()
        {
            this.CARs = new HashSet<CAR>();
        }
    
        public int CMODEL_ID { get; set; }
        public Nullable<int> CMAKE_ID { get; set; }
        public string CMODEL_NAME { get; set; }
        public Nullable<int> CTYPE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAR> CARs { get; set; }
        public virtual CARMAKE CARMAKE { get; set; }
        public virtual CARTYPE CARTYPE { get; set; }
    }
}
