//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_Management_System.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRENTAL
    {
        public int CRENTAL_ID { get; set; }
        public Nullable<int> CR_ID { get; set; }
        public System.DateTime CRENTAL_HIREDATE { get; set; }
        public System.DateTime CRENTAL_RETURNDATE { get; set; }
        public int CRENTAL_REQUIREDFOR { get; set; }
        public Nullable<int> CUST_ID { get; set; }
        public string CRENTAL_STATUS { get; set; }
    
        public virtual CARRENT CARRENT { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
