//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_Management_System.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARRENT()
        {
            this.CARRENTALs = new HashSet<CARRENTAL>();
        }
    
        public int CR_ID { get; set; }
        public Nullable<int> C_ID { get; set; }
        public string CR_TYPE { get; set; }
        public int CR_RENT { get; set; }
        public int CR_SDEPOSIT { get; set; }
    
        public virtual CAR CAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRENTAL> CARRENTALs { get; set; }
    }
}
