//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_Management_System.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.CARRENTALs = new HashSet<CARRENTAL>();
        }
    
        public int CUST_ID { get; set; }
        public string CUST_CNIC { get; set; }
        public string CUST_NAME { get; set; }
        public int CUST_AGE { get; set; }
        public string CUST_CONTACT { get; set; }
        public string CUST_ADDRESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRENTAL> CARRENTALs { get; set; }
    }
}
